### ISSUE TITLE
Update the govuk frontend toolkit to 4.8

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/government-frontend#104]
The version of the GOV.UK frontend toolkit used by government frontend is 2.0.1.

The most recent release of the GOV.UK frontend toolkit is 4.8.

It would be good to update it, I'd like to make use of the px-to-em function in the toolkit's `_helpers.scss`.

cc. @fofr, @dsingleton.

**Comment by dsingleton** [comment]
:+1: to upgrading the toolkit. 

I'm less certain on the use of `pem`, it's not something we use on GOV.UK, and I'm not sure if the benefit would outweigh the additional complexity of introducing _another_ way of doing things, and only in once place.

**Comment by fofr** [comment]
Closing this as service-manual-frontend is being split out from government-frontend.
