### ISSUE TITLE
Videos overlap contents sticky element

### ISSUE THREAD

**Issue by andysellick** [alphagov/government-frontend#1226]
[On this page](https://www.gov.uk/guidance/help-and-support-for-self-assessment) the videos overlap the 'Contents' link that appears at the foot of the screen as a sticky element.

![ezgif-3-f7d6d6d9d78f](https://user-images.githubusercontent.com/861310/51896658-ce0bcf80-23a4-11e9-86b2-a844f95b5d2f.gif)

**Comment by vanitabarrett** [comment]
Looks like the video player has a `z-index` of `3000` which is why this is happening
https://github.com/alphagov/govuk_frontend_toolkit/blob/03204449dcbf28c2d48e7f6dd217f6abe9b3a518/stylesheets/design-patterns/_media-player.scss#L23

**Comment by andysellick** [comment]
@kr8n3r presumably your work on the new video player will resolve this issue?

**Comment by andysellick** [comment]
This issue appears to have been resolved with the introduction of the new video player.
