### ISSUE TITLE
Links in dark blue boxes are invisible

### ISSUE THREAD

**Issue by andrewhick** [alphagov/government-frontend#1475]
On at least two guidance pages, links in dark blue boxes are appearing as dark blue, and therefore invisible:
![image](https://user-images.githubusercontent.com/18572857/64596873-a1914a80-d3ac-11e9-965c-8c89cc5c3b55.png)

Two affected pages - both Defra services:
* https://www.gov.uk/guidance/register-your-waste-exemptions-environmental-permits
* https://www.gov.uk/guidance/check-if-you-need-an-environmental-permit

From discussion with Dave House on #frontend in cross-gov Slack, it looks like an issue with this component: https://github.com/alphagov/government-frontend/blob/9695808a771e01318e7b80bed8a9478838c8c23e/app/assets/stylesheets/components/_important-metadata.scss

**Comment by maxgds** [comment]
Thanks for the report. A fix has now been deployed to live although it may take a little while for caches to expire before it's visible.
