### ISSUE TITLE
Fix wraith config and/or documentation

### ISSUE THREAD

**Issue by 36degrees** [alphagov/government-frontend#162]
I found an issue using wraith over on `service-manual-frontend`, which was originally forked from this repo. It appears to be an issue with this repo as well, so I thought it was worth at least documenting.

The current Wraith documentation and configuration seems to suggest running `wraith` from within the VM (it references localhost in the config file, and the gem is installed via bundle) but if you try to do this the stylesheets and images do not load. This is because `assets-origin.dev.gov.uk` does not resolve from within the VM, but there are no errors outputted and it took a while to work out what was going on.

I've changed the documentation in `service-manual-frontend` to suggest installing and running wraith locally instead, and modified the config to use `service-manual-frontend.dev.gov.uk` rather than `localhost`. I'm not sure that this is the correct action, but it makes it useable for now.

I guess Wraith is no longer actively being used, otherwise someone else would have seen this by now, so the alternative would be to remove it and any references from the docs?

**Comment by nickcolley** [comment]
We updated the tests here https://github.com/alphagov/government-frontend/pull/174, I've updated the development VM so the assets resolve properly.
