### ISSUE TITLE
Page titles are inconsistent based on format

### ISSUE THREAD

**Issue by andrewgarner** [alphagov/government-frontend#182]
Different formats add the document_type to the page title

https://github.com/alphagov/government-frontend/blob/master/app/views/content_items/case_study.html.erb#L2

vs

https://github.com/alphagov/government-frontend/blob/master/app/views/content_items/detailed_guide.html.erb#L2

For example a case study's title would look like 

``` html
<title>Example case study - Case study - GOV.UK</title>
```

whereas a detailed guide currently looks like

``` html
<title>Example detailed guide</title>
```

These should be consistent.

**Comment by tijmenb** [comment]
I believe the consolidation work has fixed these issues.
