### ISSUE TITLE
Document footer and metadata have inconsistent labels for the same data

### ISSUE THREAD

**Issue by nickcolley** [alphagov/government-frontend#184]
https://github.com/alphagov/government-frontend/pull/183#discussion_r79644934

![](https://cloud.githubusercontent.com/assets/2715/18677944/6ac5d07c-7f52-11e6-989f-778a015b71ac.png)

![](https://cloud.githubusercontent.com/assets/2715/18677945/6ace2290-7f52-11e6-967b-70b9ce9b6a8b.png)

**Comment by nickcolley** [comment]
We plan on removing the metadata duplication in the document footer so can close this once that's done.

**Comment by fofr** [comment]
"First published" is now "Published" in the metadata component:
https://github.com/alphagov/static/pull/1014
