### ISSUE TITLE
Step-by-step navigation and govuk-sticky-element overlap at certain scroll position

### ISSUE THREAD

**Issue by alex-ju** [alphagov/government-frontend#1921]
Step-by-step navigation and govuk-sticky-element overlap at certain scroll position

Page example: https://www.gov.uk/guidance/export-licences-and-certificates-from-1-january-2021

<img width="1049" alt="Screenshot 2020-11-20 at 19 40 55" src="https://user-images.githubusercontent.com/788096/99843018-c3698e00-2b68-11eb-877f-02dd89e2c923.png">

**Comment by andysellick** [comment]
Example doesn't work anymore for some reason, here's an alternative: https://www.gov.uk/guidance/vat-on-goods-exported-from-the-uk-notice-703

**Comment by alex-ju** [comment]
I still see it on that page at a certain scroll position
<img width="1437" alt="Screenshot 2021-01-14 at 09 56 41" src="https://user-images.githubusercontent.com/788096/104575226-d40d2080-564e-11eb-8f8a-bc803f34e533.png">

**Comment by andysellick** [comment]
Fixed.
