### ISSUE TITLE
Department page crest has link colour

### ISSUE THREAD

**Issue by kr8n3r** [alphagov/government-frontend#1976]
See https://www.gov.uk/government/organisations/department-for-education/about/recruitment for example

![Screenshot 2021-01-13 at 16 03 26](https://user-images.githubusercontent.com/3758555/104477525-1dab2c00-55b9-11eb-99ae-aeef0efd8118.png)

overzealous

```
.corporate-information-page .department-for-education-brand-colour a {
    color: #347ca9;
}
```

**Comment by owenatgov** [comment]
Made redundant by https://github.com/alphagov/government-frontend/pull/2129 Closing!
