### ISSUE TITLE
Sticky contents/print component conflicts with "Help us improve"

### ISSUE THREAD

**Issue by danielroseman** [alphagov/government-frontend#2068]
Hi GOV.UK folks,

Not sure if this is still the right repo (my knowledge of the frontend architecture is a bit out of date) but I noticed this conflict on an HTML publication page when the "Help us improve" survey is expanded:

![image](https://user-images.githubusercontent.com/131395/113405202-58935380-93a1-11eb-96d1-d9fb375471d3.png)

**Comment by andysellick** [comment]
Thanks for this @danielroseman. Can you provide a specific URL and tell us what browser you're using? Thanks

**Comment by danielroseman** [comment]
It was https://www.gov.uk/government/publications/police-crime-sentencing-and-courts-bill-2021-factsheets/police-crime-sentencing-and-courts-bill-2021-protest-powers-factsheet but unfortunately I can no longer reproduce it.

**Comment by andysellick** [comment]
Thanks for the details. I can't reproduce it either, but if I try hard I can make it glitch slightly. I think there's a case to be made for ditching the JS approach here and go with CSS position sticky instead. Apart from Internet Explorer the support is quite good now ([caniuse](https://caniuse.com/css-sticky)).

**Comment by andysellick** [comment]
This page has now been reworked to remove the JavaScript to keep the contents in view and use CSS sticky instead, so I'm marking this issue as closed.
