### ISSUE TITLE
Share links need [rel=noopener]

### ISSUE THREAD

**Issue by nickcolley** [alphagov/government-frontend#217]
We link externally to Facebook and Twitter on pages like https://www.gov.uk/government/consultations/allowing-learner-drivers-to-have-driving-lessons-on-motorways

We're using `[target=_blank]` which has a vulnerability (https://mathiasbynens.github.io/rel-noopener/) we can add `[rel=noopener]` in these cases.

**Comment by fofr** [comment]
We should apply this to the older share links in Whitehall too.
