### ISSUE TITLE
Service manual pages not aligned correctly on mobile and tablet

### ISSUE THREAD

**Issue by MartinJJones** [alphagov/government-frontend#3250]
## What

Review and update the page templates used to render the service manual so the content sections align correctly on mobile and tablet.

### Example page

<img width="480" alt="Screenshot 2024-07-02 at 11 18 24" src="https://github.com/alphagov/government-frontend/assets/28779939/e29cff14-2319-4e2c-9a62-ce21a599c6d3">

https://www.integration.publishing.service.gov.uk/service-manual/helping-people-to-use-your-service

## Why

Updating the template will ensure we have a consistent layout used on different devices across GOV.UK. At smaller screen sizes the text can appear quite squashed, this may be a bigger issue when moving to 19px font sizes on mobile.

**Comment by CodeSonia** [comment]
This PR: https://github.com/alphagov/government-frontend/pull/3295 addresses this issue and resolves it.
