### ISSUE TITLE
HTML publications don't use govuk-frontend grid classes

### ISSUE THREAD

**Issue by andysellick** [alphagov/government-frontend#3329]
On pages like https://www.gov.uk/government/publications/car-show-me-tell-me-vehicle-safety-questions/car-show-me-tell-me-vehicle-safety-questions the columns use custom layout CSS despite being inside a `govuk-grid-row`, i.e.

- left one quarter contents column is `govuk-grid-column-one-quarter-from-desktop`
- right 3/4 column is `main-content-container`

I've done a quick test and replacing these with `govuk-grid-column-one-quarter` and `govuk-grid-column-three-quarters` seems to produce exactly the same result. There is another non-column element inside this grid row (see issue below) which may be related to this.

Possibly related to https://github.com/alphagov/government-frontend/issues/3328

**Comment by matthillco** [comment]
This is fixed in PR #3332.
