### ISSUE TITLE
rescue NameError does not display proper error page

### ISSUE THREAD

**Issue by nickcolley** [alphagov/government-frontend#378]
As seen in production from the following error:

https://errbit.publishing.service.gov.uk/apps/546493f90da1150e4e001cfc/problems/593e962a65786340e1f14500

![screen shot 2017-06-12 at 14 55 19](https://user-images.githubusercontent.com/2445413/27037225-32680800-4f7f-11e7-8edc-302c194dd802.png)

We may be able to capture this error and render the normal oops page.

**Comment by tijmenb** [comment]
I think this behaviour has been replaced and we longer do `rescue NameError`.
