### ISSUE TITLE
Contents list multi line links not underlined correctly in Firefox

### ISSUE THREAD

**Issue by andysellick** [alphagov/government-frontend#428]
Firefox (latest version) doesn't underline some of the elements correctly in the focus state (not a big problem, just being thorough). Not a regression, currently happening on live.

Chrome (correct):

<img width="905" alt="screen shot 2017-08-07 at 12 19 03" src="https://user-images.githubusercontent.com/861310/29024589-aad74604-7b6a-11e7-9b3d-5f4571516330.png">

Firefox (um):

<img width="899" alt="screen shot 2017-08-07 at 12 19 12" src="https://user-images.githubusercontent.com/861310/29024599-b29d6af8-7b6a-11e7-8a09-3e440078713a.png">

Firefox (live site):

<img width="298" alt="screen shot 2017-08-07 at 12 27 23" src="https://user-images.githubusercontent.com/861310/29024850-e6d983be-7b6b-11e7-96e5-a23c919fb8b3.png">

Increasing the line height to 1.4em fixes this.

**Comment by tijmenb** [comment]
Now tracked here, since the component has moved to the gem: https://trello.com/c/u1Z3Vbab/45-improve-contents-list-component-on-firefox
