### ISSUE TITLE
Contents list focus state has white lines in Firefox

### ISSUE THREAD

**Issue by andysellick** [alphagov/government-frontend#430]
Firefox (latest) does some more odd things on numbered items (only) when focussed. That white gap top and bottom seems to vary in width from item to item. Not a regression, already happening on live.

I think this is being caused by the line height on the spans being slightly different from that on the link - so the outer yellow border lifts away from the background colour on the focussed element. Try slowly decreasing the line height in the inspector to see it in action.

<img width="308" alt="screen shot 2017-08-07 at 12 20 44" src="https://user-images.githubusercontent.com/861310/29024645-ed853470-7b6a-11e7-9c22-db5eaf8c3aec.png">

<img width="346" alt="screen shot 2017-08-07 at 12 20 56" src="https://user-images.githubusercontent.com/861310/29024651-f2bfa182-7b6a-11e7-82d2-36185c2fa56f.png">

**Comment by tijmenb** [comment]
Now tracked here, since the component has moved to the gem: https://trello.com/c/u1Z3Vbab/45-improve-contents-list-component-on-firefox
