### ISSUE TITLE
Rescue from GdsApi::HTTPGone

### ISSUE THREAD

**Issue by kevindew** [alphagov/government-frontend#437]
There are rescue blocks for a bunch of the status codes that content store can return in [content_items_controller.rb](https://github.com/alphagov/government-frontend/blob/master/app/controllers/content_items_controller.rb#L4-L6) however there isn't one to handle a 410 response.

With the [Publishing E2E Tests](https://github.com/alphagov/publishing-e2e-tests) we've seen an issue occur which causes government frontend to 500:

- Content is unpublished, but hasn't reached content-store yet
- A user requests a piece of content
- Router sends user to government-frontend
- The content-store is updated with the unpublishing
- government-frontend accesses content-store and receives a [410 response](https://github.com/alphagov/content-store/blob/master/app/controllers/content_items_controller.rb#L135) 
- government frontend doesn't know how to rescue a `GdsApi::HTTPGone` error, so raises a 500

I haven't been able to find any evidence of this happening in production environment.

**Comment by fofr** [comment]
This may also be true for redirects:
https://errbit.publishing.service.gov.uk/apps/546493f90da1150e4e001cfc/problems/598d8f8c65786378a687c400

**Comment by kevindew** [comment]
I've got https://github.com/alphagov/government-frontend/pull/725 open which should resolve the immediate issue in this card.

The related issue with redirects seems a thornier issue to resolve since Content Store doesn't return a list of redirects with a response and we would need some logic to determine which one to use for a redirect.
