### ISSUE TITLE
Banner component can contain information before the heading, making it inaccessible to screenreaders

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/government-frontend#441]
The way the banner component has been implemented means that if an aside is provided, the aside  is above the banner heading in the DOM. This makes it highly likely that screen reader users will miss the aside content. All content needs to follow the heading.

**Current:**
<img width="412" alt="screen shot 2017-08-11 at 16 10 07" src="https://user-images.githubusercontent.com/29889908/29219404-d6ba0eee-7eaf-11e7-8126-3210d1ce4fa2.png">

**Comment by fofr** [comment]
Fixed by #470
