### ISSUE TITLE
RTL breaks metadata layout on small screens

### ISSUE THREAD

**Issue by andysellick** [alphagov/government-frontend#509]
On [this Arabic news article](http://government-frontend.dev.gov.uk/government/news/foreign-secretary-article-on-the-balfour-declaration.ar) and shortly on the [same version in Hebrew](http://government-frontend.dev.gov.uk/government/news/foreign-secretary-article-on-the-balfour-declaration.he) the metadata layout gets broken at small screen sizes. See screenshots.

![screen shot 2017-10-30 at 17 03 58](https://user-images.githubusercontent.com/861310/32184517-5c3d5e04-bd94-11e7-8256-c50e5968bb12.png)

![screen shot 2017-10-30 at 16 59 37](https://user-images.githubusercontent.com/861310/32184522-604cbec2-bd94-11e7-84dc-9ef2b777bbaa.png)

**Comment by nickcolley** [comment]
Think this should be raised on static, since the component lives there.

**Comment by andysellick** [comment]
Re-raised on static - https://github.com/alphagov/static/issues/1207
