### ISSUE TITLE
Investigate using Chrome instead of PhantomJS for integration tests

### ISSUE THREAD

**Issue by nickcolley** [alphagov/government-frontend#666]
https://robots.thoughtbot.com/headless-feature-specs-with-chrome

1. Chrome headless may be a better long term bet than PhantomJS
2. It may improve the speed of our tests

Thanks to @kevindew for the suggestion.

**Comment by tijmenb** [comment]
Now being tracked here: https://trello.com/c/vfrnbD8a/52-use-replacement-for-phantomjs
