### ISSUE TITLE
Document lists at the bottom of a collection look like they are missing an item

### ISSUE THREAD

**Issue by fofr** [alphagov/government-frontend#744]
The border at the bottom of the document list combined with the top border of the "Published" component creates a space that looks like a missing document.

https://www.gov.uk/government/collections/hmrcs-annual-report-and-accounts

![screen shot 2018-02-09 at 09 21 46](https://user-images.githubusercontent.com/319055/36020820-db2371e0-0d7b-11e8-85cd-d8b65e66acca.png)

**Comment by KyleMacPherson** [comment]
We received a zendesk ticket on this issue today (08/03/2018) in which a publisher was complaining about there being a blank slot in their document list.
