### ISSUE TITLE
Related stats announcements copy misleading

### ISSUE THREAD

**Issue by fofr** [alphagov/government-frontend#745]
We use the statistics announcement document type to craft the link text, this suggests a link will show only national stats or official stats. The actual link shows all stats announcements by that organisation.

Both of the screens below point to the same URL:
https://www.gov.uk/government/statistics/announcements?departments%5B%5D=ministry-of-defence&topics%5B%5D=defence-and-armed-forces

![screen shot 2018-02-09 at 09 33 47](https://user-images.githubusercontent.com/319055/36021007-6ad7cb60-0d7c-11e8-9812-cccd93d46a2e.png)
![screen shot 2018-02-09 at 09 33 38](https://user-images.githubusercontent.com/319055/36021008-6af3b924-0d7c-11e8-96d9-dd31ed054dcd.png)

Suggest: "Related statistics announcements" instead.

**Comment by steventux** [comment]
Fixed by https://github.com/alphagov/government-frontend/pull/773
Link now reads "More statistics announcements from..." regardless of document type.
