### ISSUE TITLE
Fixed 'contents' link can obscure links

### ISSUE THREAD

**Issue by nickcolley** [alphagov/government-frontend#783]
@andysellick recently did some research with http://www.digitalaccessibilitycentre.org/ and found that their fixed navigation created a barrier for a 'dragon' user.

I noticed that this same issue can happen with the back to top contents link.

Here you can see me tabbed to a link:

![tabbing through content page](https://user-images.githubusercontent.com/2445413/36478432-99198bd8-16fc-11e8-8884-8d154a0caf64.PNG)

Then after tabbing again you can see the link is obscured:

![tabbed obscured](https://user-images.githubusercontent.com/2445413/36478431-98fcc908-16fc-11e8-9c46-8420f0201a4f.PNG)

This means that assistive technologies that rely on being able to 'see' elements to click them will not work, as was seen with Andy's team research.

@andysellick if you have any more details please share 👍

**Comment by andysellick** [comment]
I think this might be a duplicate of https://github.com/alphagov/government-frontend/issues/748

**Comment by nickcolley** [comment]
Ah so it is
